version: '3.9'

services:
  web:
    image: 127.0.0.1:5000/simple_python_web_app
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: redis:alpine
